import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "doc",
      id: "api/document-360-customer-api",
    },
    {
      type: "category",
      label: "APIReferences",
      items: [
        {
          type: "doc",
          id: "api/deletes-an-api-reference",
          label: "Deletes an API reference",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/import-the-api-reference-spec-file",
          label: "Import the API reference spec file",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/resync-the-api-reference-spec-file",
          label: "Resync the API reference spec file",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/get-all-api-reference-logs",
          label: "Get all API reference logs",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-errors-and-alerts-of-a-log",
          label: "Get errors and alerts of a log",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/publishes-an-api-reference",
          label: "Publishes an API reference",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Articles",
      items: [
        {
          type: "doc",
          id: "api/deletes-an-article-with-an-id",
          label: "Deletes an article with an ID",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/deletes-an-article-version",
          label: "Deletes an article version",
          className: "menu__list-item--deprecated api-method delete",
        },
        {
          type: "doc",
          id: "api/deletes-an-article-version",
          label: "Deletes an article version",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/delete-multiple-article-versions",
          label: "Delete multiple article versions",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/deletes-multiple-articles",
          label: "Deletes multiple articles",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/unpublishes-an-article-with-an-id",
          label: "Unpublishes an article with an id",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/publishes-an-article-with-an-id",
          label: "Publishes an article with an id",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/unpublishes-multiple-articles",
          label: "Unpublishes multiple articles",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/publishes-multiple-articles",
          label: "Publishes multiple articles",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/gets-an-article",
          label: "Gets an article",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/updates-an-article-with-the-id",
          label: "Updates an article with the ID",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/gets-an-article-by-url",
          label: "Gets an article by URL",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/adds-an-article-to-an-existing-category",
          label: "Adds an article to an existing category",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/gets-all-article-versions",
          label: "Gets all article versions",
          className: "menu__list-item--deprecated api-method get",
        },
        {
          type: "doc",
          id: "api/gets-all-article-versions",
          label: "Gets all article versions",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/gets-article-by-a-version-number",
          label: "Gets article by a version number",
          className: "menu__list-item--deprecated api-method get",
        },
        {
          type: "doc",
          id: "api/gets-article-by-a-version-number",
          label: "Gets article by a version number",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/gets-settings-for-the-article",
          label: "Gets settings for the article",
          className: "menu__list-item--deprecated api-method get",
        },
        {
          type: "doc",
          id: "api/updates-settings-for-the-article",
          label: "Updates settings for the article",
          className: "menu__list-item--deprecated api-method put",
        },
        {
          type: "doc",
          id: "api/gets-settings-for-the-article",
          label: "Gets settings for the article",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/updates-settings-for-the-article",
          label: "Updates settings for the article",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/adds-multiple-articles",
          label: "Adds multiple articles",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/publishes-an-article-with-an-id",
          label: "Publishes an article with an id",
          className: "menu__list-item--deprecated api-method post",
        },
        {
          type: "doc",
          id: "api/update-workflow-status-of-the-articles",
          label: "Update workflow status of the articles",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/forks-an-article-with-an-id",
          label: "Forks an article with an id",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/updates-multiple-articles",
          label: "Updates multiple articles",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/update-the-article-description",
          label: "Update the Article Description",
          className: "menu__list-item--deprecated api-method put",
        },
        {
          type: "doc",
          id: "api/update-the-article-description",
          label: "Update the Article Description",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "Categories",
      items: [
        {
          type: "doc",
          id: "api/deletes-an-category-with-an-id",
          label: "Deletes an category with an ID",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/get-a-category-by-id-with-its-articles-and-direct-child-categories-metadata",
          label: "Get a category by ID with its articles and direct child categories metadata",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/update-a-category-with-the-id",
          label: "Update a category with the ID",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/delete-category-version",
          label: "Delete category Version",
          className: "menu__list-item--deprecated api-method delete",
        },
        {
          type: "doc",
          id: "api/delete-category-version",
          label: "Delete category Version",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/delete-multiple-category-versions",
          label: "Delete multiple category versions",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/unpublishes-a-page-category-with-an-id",
          label: "Unpublishes a page category with an id",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/publishes-an-category-with-an-id",
          label: "Publishes an category with an id",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/unpublishes-multiple-categories",
          label: "Unpublishes multiple categories",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/publishes-multiple-categories",
          label: "Publishes multiple categories",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/gets-a-category-by-url",
          label: "Gets a category by URL",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/adds-a-new-category",
          label: "Adds a new category",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-category-page-with-an-id",
          label: "Get category page with an ID",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/update-a-category-page-content-with-the-id",
          label: "Update a category page content with the ID",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/get-category-page-content-with-an-id",
          label: "Get category page content with an ID",
          className: "menu__list-item--deprecated api-method get",
        },
        {
          type: "doc",
          id: "api/get-category-page-content-with-an-id",
          label: "Get category page content with an ID",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-category-page-versions",
          label: "Get category page versions",
          className: "menu__list-item--deprecated api-method get",
        },
        {
          type: "doc",
          id: "api/get-category-page-versions",
          label: "Get category page versions",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-settings-for-the-category",
          label: "Get settings for the Category",
          className: "menu__list-item--deprecated api-method get",
        },
        {
          type: "doc",
          id: "api/update-settings-for-the-category",
          label: "Update settings for the category",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/get-settings-for-the-category",
          label: "Get settings for the Category",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/update-settings-for-the-category",
          label: "Update settings for the category",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/adds-multiple-categories",
          label: "Adds multiple Categories",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/publishes-an-category-with-an-id",
          label: "Publishes an category with an id",
          className: "menu__list-item--deprecated api-method post",
        },
        {
          type: "doc",
          id: "api/update-workflow-status-of-the-page-categories",
          label: "Update workflow status of the page categories",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/update-multiple-page-categories",
          label: "Update multiple page categories",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/fork-category-page-with-an-id",
          label: "Fork category page with an id",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/update-the-category-type",
          label: "Update the Category Type",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/update-the-category-description",
          label: "Update the category description",
          className: "menu__list-item--deprecated api-method put",
        },
        {
          type: "doc",
          id: "api/update-the-category-description",
          label: "Update the category description",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "CustomField",
      items: [
        {
          type: "doc",
          id: "api/gets-all-custom-field-definitions",
          label: "Gets all custom field definitions.",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Drive",
      items: [
        {
          type: "doc",
          id: "api/delete-a-folder",
          label: "Delete a folder",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/gets-folder-information-by-folder-id",
          label: "Gets folder information by folder ID",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/delete-file-using-file-id",
          label: "Delete file using file ID",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/gets-file-information",
          label: "Gets file information",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/move-a-file-with-file-id",
          label: "Move a file with file ID",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/gets-folders-information",
          label: "Gets folders information",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/add-new-folder-in-drive",
          label: "Add new folder in drive",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/update-a-folder-with-id",
          label: "Update a folder with ID",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/drive-search-files-and-folders",
          label: "Drive search - files and folders",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-status-of-the-delete-file-operation",
          label: "Get status of the delete file operation",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-all-media-files-inserted-in-the-article",
          label: "Get all media files inserted in the article",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/add-file-in-to-drive",
          label: "Add file in to drive",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/add-tags-in-a-file-using-file-id",
          label: "Add tags in a file using file ID",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/delete-tags-from-files",
          label: "Delete tags from files",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/copy-file-from-one-folder-to-another",
          label: "Copy file from one folder to another",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Language",
      items: [
        {
          type: "doc",
          id: "api/gets-all-version-languages-in-the-project",
          label: "Gets all version languages in the project",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Project",
      items: [
        {
          type: "doc",
          id: "api/get-the-status-of-export",
          label: "Get the status of export",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/gets-all-workflow-statuses-for-a-project",
          label: "Gets all workflow statuses for a project",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-the-status-of-import",
          label: "Get the status of import",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-all-the-schemes-for-the-project",
          label: "Get all the schemes for the project",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-a-document-article-or-category-by-url-path",
          label: "Get a document (article or category) by URL path",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/start-a-new-export",
          label: "Start a new export",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/import-documentation",
          label: "Import documentation",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "ProjectVersions",
      items: [
        {
          type: "doc",
          id: "api/gets-list-of-project-versions",
          label: "Gets list of project versions",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/searches-for-a-phrase-inside-project-version",
          label: "Searches for a phrase inside project version",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/gets-list-of-categories-within-project-version",
          label: "Gets list of categories within project version",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/gets-list-of-articles-within-a-project-version",
          label: "Gets list of articles within a project version",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/gets-list-of-api-reference-within-project-version",
          label: "Gets list of api reference within project version",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/perform-ai-assistive-search-within-project-version",
          label: "Perform AI assistive search within project version",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/provide-feedback-for-ai-assistive-search",
          label: "Provide feedback for AI assistive search",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Readers",
      items: [
        {
          type: "doc",
          id: "api/deletes-a-reader-from-the-project",
          label: "Deletes a reader from the project",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/updates-a-reader",
          label: "Updates a reader",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/deletes-a-reader-group",
          label: "Deletes a reader group",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/get-a-reader-group-via-group-id",
          label: "Get a reader group via group id",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/updates-a-reader-group",
          label: "Updates a reader group",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/deletes-jwt-readers-from-the-project",
          label: "Deletes JWT readers from the project",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/get-all-available-readers-from-the-project",
          label: "Get all available readers from the project",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/add-a-new-reader",
          label: "Add a new reader",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-all-reader-groups",
          label: "Get all reader groups",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/add-a-new-reader-group",
          label: "Add a new reader group",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Teams",
      items: [
        {
          type: "doc",
          id: "api/deletes-a-user-with-an-id",
          label: "Deletes a user with an ID",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/get-complete-user-details-by-id",
          label: "Get complete user details by id",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-all-user-groups",
          label: "Get all user groups",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/checks-if-email-already-exists-in-the-project",
          label: "Checks if email already exists in the project",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-all-team-accounts",
          label: "Get all team accounts",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/adds-a-new-team-account",
          label: "Adds a new Team Account",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-all-available-roles-including-default-as-well-as-custom-roles",
          label: "Get all available roles including default as well as custom roles",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/update-the-portal-role-of-a-individual-user",
          label: "Update the portal role of a individual user",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/update-the-content-roles-of-an-individual-user",
          label: "Update the content roles of an individual user",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/modify-the-groups-associated-with-the-user",
          label: "Modify the groups associated with the user",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "Translations",
      items: [
        {
          type: "doc",
          id: "api/gets-articles-by-translation-status",
          label: "Gets articles by translation status",
          className: "api-method get",
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
